language: python
cache: pip
python:
    - 2.7
    - 3.6
    #- nightly
    #- pypy
    #- pypy3
matrix:
    allow_failures:
        - python: nightly
        - python: pypy
        - python: pypy3
install:
    pip install -r requirements.txt
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down